# Generated by Django 4.1.7 on 2023-03-20 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('day_of_week', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration', models.IntegerField()),
                ('schedule_status', models.CharField(max_length=50)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='slot',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_time', models.TimeField()),
                ('slot_date', models.DateField()),
                ('slot_status', models.CharField(max_length=50)),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appoitments.doctor_schedule')),
            ],
        ),
        migrations.CreateModel(
            name='booked_appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('appointment_date', models.DateField()),
                ('appointment_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('slot_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Appoitments.slot')),
            ],
        ),
    ]
