# Generated by Django 4.1.7 on 2023-03-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appoitments', '0002_alter_doctor_schedule_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked_appointment',
            name='status',
            field=models.CharField(choices=[('pend', 'pending'), ('comp', 'completed'), ('canc', 'cancelled')], max_length=50),
        ),
    ]
