# Generated by Django 4.1.7 on 2023-03-20 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appoitments', '0003_alter_booked_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_schedule',
            name='slot_duration',
            field=models.IntegerField(choices=[(5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55), (60, 60)]),
        ),
        migrations.CreateModel(
            name='slots',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_start_time', models.TimeField()),
                ('slot_end_time', models.TimeField()),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appoitments.doctor_schedule')),
            ],
        ),
        migrations.AlterField(
            model_name='booked_appointment',
            name='slot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Appoitments.slots'),
        ),
        migrations.DeleteModel(
            name='slot',
        ),
    ]
