# Generated by Django 4.1.7 on 2023-03-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appoitments', '0004_alter_doctor_schedule_slot_duration_slots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_schedule',
            name='schedule_status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=50),
        ),
    ]
