# Generated by Django 4.1.7 on 2023-03-21 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appoitments', '0005_alter_doctor_schedule_schedule_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booked_appointment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='booked_appointment',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='doctor_schedule',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='doctor_schedule',
            name='object_id',
        ),
    ]
