# Generated by Django 4.1.7 on 2023-03-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appoitments', '0007_rename_slots_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked_appointment',
            name='appointment_type',
            field=models.CharField(choices=[('new', 'new'), ('followup', 'followup')], max_length=50),
        ),
    ]
